/**
 * Port. Identity generation.
 *
 * Ids are generated by the Application layer (not by the database) so that an
 * aggregate is complete and referenceable *before* it is persisted, and so the
 * domain never depends on `node:crypto`.
 */
export interface IdGenerator {
  generate(): string;
}
